model_path: 'model/best.pt'
images_path: '/home/zhiqics/sanjian/dataset/images/Train'
detection_conf_thresh: 0.1
gpu_avail: False #True
img_format: .jpg #or any other format supported by YOLO
img_width: 960
img_height: 540
blur_radius: 31 #increase to increase blur intensity (odd values)
output_folder: /home/zhiqics/sanjian/dataset/images/Train_anonymized_coco
# COCO specific settings
use_coco_labels: true
coco_annotation_file: '/home/zhiqics/sanjian/dataset/annotations/instances_Train.json'
# Class mapping for COCO to YOLO (optional, can be customized)
class_mapping:
  person: 0      # faces detected from person class
  face: 0        # if you have face annotations
  license_plate: 1
  text: 2        # anonymize text regions
  car: -1        # ignore cars
  truck: -1      # ignore trucks
  bus: -1        # ignore buses
